import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#6f5c00",
        "tertiary-container": "#ff8e72",
        "surface-container-low": "#191c22",
        "on-tertiary": "#621100",
        background: "#10131a",
        "surface-container-highest": "#32353c",
        "on-secondary": "#3a3000",
        "primary-fixed-dim": "#3ce36a",
        "on-background": "#e1e2eb",
        "on-primary-container": "#004c1b",
        "secondary-fixed": "#ffe170",
        primary: "#3fe56c",
        "inverse-primary": "#006e2a",
        "tertiary-fixed": "#ffdad2",
        tertiary: "#ffb7a6",
        "surface-bright": "#363940",
        "primary-fixed": "#69ff87",
        "on-tertiary-fixed": "#3c0700",
        secondary: "#fff3d2",
        "on-error-container": "#ffdad6",
        error: "#ffb4ab",
        "on-tertiary-fixed-variant": "#8a1d00",
        "error-container": "#93000a",
        "inverse-on-surface": "#2e3037",
        "primary-container": "#00c853",
        "on-primary": "#003912",
        "inverse-surface": "#e1e2eb",
        "on-error": "#690005",
        "surface-container-high": "#272a31",
        "on-surface": "#e1e2eb",
        "on-secondary-fixed": "#221b00",
        outline: "#869583",
        "on-primary-fixed": "#002108",
        "on-secondary-fixed-variant": "#544600",
        "surface-variant": "#32353c",
        "surface-container-lowest": "#0b0e14",
        "on-surface-variant": "#bbcbb8",
        surface: "#10131a",
        "secondary-container": "#fdd400",
        "tertiary-fixed-dim": "#ffb4a2",
        "surface-dim": "#10131a",
        "outline-variant": "#3c4a3c",
        "secondary-fixed-dim": "#e9c400",
        "surface-tint": "#3ce36a",
        "surface-container": "#1d2026",
        "on-tertiary-container": "#7f1a00",
        "on-primary-fixed-variant": "#00531e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
