services:
  us-stock:
    build:
      context: .
    container_name: us-stock
    ports:
      - "8889:8889"
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=8889
      - TZ=America/New_York
    restart: unless-stopped
